### ISSUE TITLE
Dimensions panel not loaded for Rio Grande Do Sul package

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#16]
When viewing this package:

https://raw.githubusercontent.com/os-data/boost-rio-grande-do-sul-revenue/master/datapackage.json

The dimensions panel does not load in the UI, yet there are dimensions in the `datapackage.json`

**Comment by danfowler** [comment]
You should use this version instead.  I'll remove these os-data versions: https://github.com/openspending/fiscal-data-package-demos/blob/master/boost-rio-grande-do-sul-state-revenue/datapackage.json

**Comment by kravets-levko** [comment]
@pwalsh This bug was caused by invalid datapackage file. Currently @danfowler has fixed package, so this issue may be closed.

**Comment by pwalsh** [comment]
yes correct, thanks.
